### ISSUE TITLE
Recipe Task List

### ISSUE THREAD

**Issue by KyleKing** [KyleKing/recipes#13]
* [ ] Recipes
    * [ ] dark-chocolate-mousse-cake: https://sallysbakingaddiction.com/dark-chocolate-mousse-cake/
    * [ ] Joy of Cooking - Burritos, Mixed Drinks, etc.
    * [ ] Salads: https://www.thekitchn.com/tips-for-making-restaurant-quality-salad-232510?utm_source=theskimm&utm_medium=social&utm_campaign=swap
* [ ] Sandwiches: Balsamic, Tomato, Mozz, Basil
